name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Metadata action
      uses: docker/metadata-action@v5.0.0
      with:
        images: |
          waypointer
        tags: |
          type=sha
        github-token: ${{ github.token }}
          
    
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.0.0
      
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{github.token}}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        push: true
        github-token: ${{ github.token }}     
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
